baseUrl="https://kedadiannao220.github.io"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "penggy Blog"
Theme = "maupassant"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "pengganyu"


[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3
