baseURL = "https://xibolun.github.io" # <head> 里面的 baseurl 信息，填你的博客地址
title = "penggy blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 (需要自己下载)


paginate = 20 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt


preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 10

  [[menu.main]]
    name = "Tools"
    url = "/tags/tool/"
    weight = 20

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    name = "读书"
    url = "/books"
    weight = 42


  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

[params]
    since = 2017
    author = "pengganyu"                          # Author's name
    avatar = "/blog-images/r/me/avatar.jpg"           # Author's avatar
    subtitle = "Just for Fun"                  # Subtitle
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = ""

    description = "Mogeko 的个人博客" # (Meta) 描述

    beian = ""
    googleAnalytics = "UA-101106729-1" # Google 统计 id

    busuanzi = true # 不蒜子计数
    # license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "621dd77636c317069337" # Your client ID
    clientSecret = "614d7596d823c41978f49c5434301ba8304da7d5" # Your client secret
    repo = "blog-commits" # The repo to store comments
    owner = "Mogeko" # Your GitHub ID
    admin= "Mogeko" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

[params.utteranc] # Homepage: https://utteranc.es
    repo = "xibolun/blog-comment" # The repo to store comments
    issueTerm = "title" # the mapping between blog posts and GitHub issues. 
    theme = "github-light" # Theme
    crossorigin = "anonymous" # default: anonymous