baseUrl="https://xibolun.github.io"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "penggy Blog"
Theme = "maupassant"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"
DisqusShortname = "http-xibolun-github-io"
googleAnalytics = "UA-101106729-1"



[Author]
  Name = "pengganyu"

[params]
  busuanzi = true

[menu]
  [[menu.main]]
    identifier = "books"
    name = "读书"
    url = "/books/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3
